version: '3.8'
services:
  booking:
    build: ./MicroServices/BookingService
    ports:
      - '5000:5000'
    volumes:
      - ./MicroServices/BookingService:/app
  app:
    build: ./MainApp
    ports:
      - '5001:5001'
    volumes:
      - ./MainApp:/app
    depends_on:
      - booking
        
