version: '3.8'
services:
  booking:
    build: ./MicroServices/BookingService
    ports:
      - '5000:5000'
    # volumes:
    #   - ./MicroServices/BookingService:/app
    env_file:
      - ./env
  app:
    build: ./MainApp
    ports:
      - '5001:5001'
    # volumes:
    #   - ./MainApp:/app
    env_file:
      - ./env
    depends_on:
      - booking
        
