version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
  booking:
    build: ./Microservices/BookingService
    ports:
      - '5000:5000'
    volumes:
      - ./Microservices/BookingService:/app
    env_file:
      - ./env
    depends_on:
      - mongodb
  app:
    build: ./MainApp
    ports:
      - '5001:5001'
    volumes:
      - /home/yogesh-kumar/Projects/ODA/MainApp:/app
    env_file:
      - ./env
    depends_on:
      - booking
volumes:
  data:
        